---
dev_addr: "127.0.0.1:8001"
edit_uri: "blob/main/docs"
site_name: "Pylint Nautobot Documentation"
site_url: "https://docs.nautobot.com/projects/pylint-nautobot/en/latest/"
repo_url: "https://github.com/nautobot/pylint-nautobot"
copyright: "Copyright &copy; The Authors"
theme:
  name: "material"
  navigation_depth: 4
  custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "navigation.indexes"
    - "navigation.tracking"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.footer"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
    - "content.code.copy"
    - "content.action.edit"
    - "content.action.view"
  favicon: "assets/favicon.ico"
  logo: "assets/nautobot_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
extra_css:
  - "assets/extra.css"

# needed for RTD version flyout menu
# jquery is not (yet) injected by RTD automatically and it might be dropped
# as a dependency in the future
extra_javascript:
  - "https://code.jquery.com/jquery-3.6.0.min.js"

extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/blog/tags/nautobot"
      name: "Network to Code Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/playlist?list=PLjA0bhxgryJ2Ts4GJMDA-tPzVWEncv4pb"
      name: "Nautobot Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "Network to Code Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/nautobot/nautobot"
      name: "GitHub Repo"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "Network to Code Twitter"
markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "footnotes"
plugins:
  - "search"
  - "mkdocs-version-annotations"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            show_root_heading: true
  - "macros":
      module_name: "docs/macros"
      on_error_fail: true
      on_undefined: "strict"
      render_by_default: false  # Only enable macros and Jinja2 rendering on specific pages
watch:
  - "README.md"

nav:
  - Overview: "index.md"
  - Getting Started: "getting_started.md"
  - Release Notes: "release_notes.md"
  - Development: "development.md"
  - Rules: "rules.md"
  - Nautobot Docs Home ↗︎: "https://docs.nautobot.com"
