[tool.poetry]
name = "pylint-nautobot"
version = "0.1.0"
description = "Custom Pylint Rules for Nautobot"
authors = ["Cristian Sirbu <cristian.sirbu@networktocode.com>", "Leo Kirchner <leo.kirchner@networktocode.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pylint = "^2.13"
pyyaml = "^6.0"
importlib-resources = "^5.12.0"
tomli = "^2.0.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pydocstyle = "^6.3.0"
flake8 = "^3.9.2"
bandit = "^1.7.5"
invoke = "^2.0.0"
toml = "^0.10.2"
yamllint = "^1.30.0"
pytest = "^7.3.0"
# Rendering docs to HTML
mkdocs = "~1.4.3"
# Material for MkDocs theme
mkdocs-material = "9.1.14"
# Render custom markdown for version added/changed/remove notes
mkdocs-version-annotations = "1.0.0"
# Automatic documentation from sources, for MkDocs
mkdocstrings = "0.21.2"
mkdocstrings-python = "0.10.1"

[tool.pylint-nautobot]
# Normally this configuration goes into the apps that should be linted, but this is required so that the checkers
# activate correctly during unit testing.
supported_nautobot_versions = [
    "1",
    "2"
]

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | settings.py     # This is where you define files that should not be stylized by black
                     # the root of the project
)
'''

[tool.pylint.master]
ignore=".venv"

[tool.pylint.basic]
# No docstrings required for private methods (Pylint default), or for test_ functions, or for inner Meta classes.
no-docstring-rgx="^(_|test_|Meta$|visit_)"

[tool.pylint.messages_control]
# Line length is enforced by Black, so pylint doesn't need to check it.
# Pylint and Black disagree about how to format multi-line arrays; Black wins.
disable = """,
    line-too-long
    """

[tool.pylint.miscellaneous]
# Don't flag TODO as a failure, let us commit with things that still need to be done in the code
notes = """,
    FIXME,
    XXX,
    """

[tool.pydocstyle]
convention = "google"
inherit = false
match = "(?!__init__).*\\.py"
match-dir = "(?!tests|migrations|development|visit_)[^\\.].*"
# D212 is enabled by default in google convention, and complains if we have a docstring like:
# """
# My docstring is on the line after the opening quotes instead of on the same line as them.
# """
# We've discussed and concluded that we consider this to be a valid style choice.
# D012 is enforced by pylint as well, doubling up here provides no additional value.
add_ignore = "D102, D212"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
norecursedirs = [
    "tests/input"
]
addopts = "-vv --doctest-modules"

[tool.bandit]
skips = []
# No need to check for security issues in the test scripts!
exclude_dirs = ["./tests/", "./.venv/"]
