[tool.poetry]
name = "pylint-nautobot"
version = "0.1.0"
description = "Custom Pylint Rules for Nautobot"
authors = ["Cristian Sirbu <cristian.sirbu@networktocode.com>", "Leo Kirchner <leo.kirchner@networktocode.com>"]
readme = "README.md"
packages = [{include = "pylint_nautobot"}]

[tool.poetry.dependencies]
python = "^3.7"
pylint = "^2.13"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
